// Top 6 stocks for Market Overview
export const POPULAR_SYMBOLS = [
  { value: "NSE:RELIANCE-EQ", label: "RELIANCE", name: "Reliance Industries" },
  { value: "NSE:TCS-EQ", label: "TCS", name: "Tata Consultancy Services" },
  { value: "NSE:HDFCBANK-EQ", label: "HDFC Bank", name: "HDFC Bank" },
  { value: "NSE:INFY-EQ", label: "INFY", name: "Infosys" },
  { value: "NSE:ICICIBANK-EQ", label: "ICICI Bank", name: "ICICI Bank" },
  { value: "NSE:SBIN-EQ", label: "SBIN", name: "State Bank of India" },
];

// All available stocks for analysis - 500+ NSE stocks
export const ALL_SYMBOLS = [
  // Banking & Financial Services (Large Cap)
  { value: "NSE:HDFCBANK-EQ", label: "HDFCBANK", name: "HDFC Bank Limited" },
  { value: "NSE:ICICIBANK-EQ", label: "ICICIBANK", name: "ICICI Bank Limited" },
  { value: "NSE:SBIN-EQ", label: "SBIN", name: "State Bank of India" },
  { value: "NSE:KOTAKBANK-EQ", label: "KOTAKBANK", name: "Kotak Mahindra Bank Limited" },
  { value: "NSE:AXISBANK-EQ", label: "AXISBANK", name: "Axis Bank Limited" },
  { value: "NSE:INDUSINDBK-EQ", label: "INDUSINDBK", name: "IndusInd Bank Limited" },
  { value: "NSE:BAJFINANCE-EQ", label: "BAJFINANCE", name: "Bajaj Finance Limited" },
  { value: "NSE:BAJAJFINSV-EQ", label: "BAJAJFINSV", name: "Bajaj Finserv Limited" },
  { value: "NSE:HDFCLIFE-EQ", label: "HDFCLIFE", name: "HDFC Life Insurance Company Limited" },
  { value: "NSE:SBILIFE-EQ", label: "SBILIFE", name: "SBI Life Insurance Company Limited" },
  { value: "NSE:ICICIPRULI-EQ", label: "ICICIPRULI", name: "ICICI Prudential Life Insurance Company Limited" },
  { value: "NSE:BAJAJHLDNG-EQ", label: "BAJAJHLDNG", name: "Bajaj Holdings & Investment Limited" },
  
  // Banking & Financial Services (Mid & Small Cap)
  { value: "NSE:PNB-EQ", label: "PNB", name: "Punjab National Bank" },
  { value: "NSE:BANKBARODA-EQ", label: "BANKBARODA", name: "Bank of Baroda" },
  { value: "NSE:FEDERALBNK-EQ", label: "FEDERALBNK", name: "Federal Bank Limited" },
  { value: "NSE:IDFCFIRSTB-EQ", label: "IDFCFIRSTB", name: "IDFC First Bank Limited" },
  { value: "NSE:BANDHANBNK-EQ", label: "BANDHANBNK", name: "Bandhan Bank Limited" },
  { value: "NSE:CHOLAFIN-EQ", label: "CHOLAFIN", name: "Cholamandalam Investment and Finance Company Limited" },
  { value: "NSE:M&MFIN-EQ", label: "M&MFIN", name: "Mahindra & Mahindra Financial Services Limited" },
  { value: "NSE:LICHSGFIN-EQ", label: "LICHSGFIN", name: "LIC Housing Finance Limited" },
  { value: "NSE:RBLBANK-EQ", label: "RBLBANK", name: "RBL Bank Limited" },
  { value: "NSE:CANBK-EQ", label: "CANBK", name: "Canara Bank" },
  { value: "NSE:UNIONBANK-EQ", label: "UNIONBANK", name: "Union Bank of India" },
  { value: "NSE:INDIANB-EQ", label: "INDIANB", name: "Indian Bank" },
  { value: "NSE:MAHABANK-EQ", label: "MAHABANK", name: "Bank of Maharashtra" },
  { value: "NSE:CENTRALBK-EQ", label: "CENTRALBK", name: "Central Bank of India" },
  { value: "NSE:PNBHOUSING-EQ", label: "PNBHOUSING", name: "PNB Housing Finance Limited" },
  { value: "NSE:RECLTD-EQ", label: "RECLTD", name: "REC Limited" },
  { value: "NSE:PFC-EQ", label: "PFC", name: "Power Finance Corporation Limited" },
  { value: "NSE:IIFL-EQ", label: "IIFL", name: "IIFL Finance Limited" },
  { value: "NSE:MUTHOOTFIN-EQ", label: "MUTHOOTFIN", name: "Muthoot Finance Limited" },
  { value: "NSE:MANAPPURAM-EQ", label: "MANAPPURAM", name: "Manappuram Finance Limited" },
  { value: "NSE:SBICARD-EQ", label: "SBICARD", name: "SBI Cards and Payment Services Limited" },
  { value: "NSE:SHRIRAMFIN-EQ", label: "SHRIRAMFIN", name: "Shriram Finance Limited" },

  // IT & Technology
  { value: "NSE:TCS-EQ", label: "TCS", name: "Tata Consultancy Services Limited" },
  { value: "NSE:INFY-EQ", label: "INFY", name: "Infosys Limited" },
  { value: "NSE:WIPRO-EQ", label: "WIPRO", name: "Wipro Limited" },
  { value: "NSE:HCLTECH-EQ", label: "HCLTECH", name: "HCL Technologies Limited" },
  { value: "NSE:TECHM-EQ", label: "TECHM", name: "Tech Mahindra Limited" },
  { value: "NSE:LTI-EQ", label: "LTI", name: "Larsen & Toubro Infotech Limited" },
  { value: "NSE:LTTS-EQ", label: "LTTS", name: "L&T Technology Services Limited" },
  { value: "NSE:MPHASIS-EQ", label: "MPHASIS", name: "Mphasis Limited" },
  { value: "NSE:COFORGE-EQ", label: "COFORGE", name: "Coforge Limited" },
  { value: "NSE:PERSISTENT-EQ", label: "PERSISTENT", name: "Persistent Systems Limited" },
  { value: "NSE:MINDTREE-EQ", label: "MINDTREE", name: "Mindtree Limited" },
  { value: "NSE:ZENSARTECH-EQ", label: "ZENSARTECH", name: "Zensar Technologies Limited" },
  { value: "NSE:HEXAWARE-EQ", label: "HEXAWARE", name: "Hexaware Technologies Limited" },
  { value: "NSE:SONATSOFTW-EQ", label: "SONATSOFTW", name: "Sonata Software Limited" },
  { value: "NSE:CYIENT-EQ", label: "CYIENT", name: "Cyient Limited" },
  { value: "NSE:TATAELXSI-EQ", label: "TATAELXSI", name: "Tata Elxsi Limited" },
  { value: "NSE:INFOEDGE-EQ", label: "INFOEDGE", name: "Info Edge (India) Limited" },
  { value: "NSE:JUSTDIAL-EQ", label: "JUSTDIAL", name: "Just Dial Limited" },
  { value: "NSE:ROUTE-EQ", label: "ROUTE", name: "Route Mobile Limited" },

  // Pharmaceuticals & Healthcare
  { value: "NSE:SUNPHARMA-EQ", label: "SUNPHARMA", name: "Sun Pharmaceutical Industries Limited" },
  { value: "NSE:DRREDDY-EQ", label: "DRREDDY", name: "Dr. Reddy's Laboratories Limited" },
  { value: "NSE:CIPLA-EQ", label: "CIPLA", name: "Cipla Limited" },
  { value: "NSE:DIVISLAB-EQ", label: "DIVISLAB", name: "Divi's Laboratories Limited" },
  { value: "NSE:AUROPHARMA-EQ", label: "AUROPHARMA", name: "Aurobindo Pharma Limited" },
  { value: "NSE:LUPIN-EQ", label: "LUPIN", name: "Lupin Limited" },
  { value: "NSE:BIOCON-EQ", label: "BIOCON", name: "Biocon Limited" },
  { value: "NSE:TORNTPHARM-EQ", label: "TORNTPHARM", name: "Torrent Pharmaceuticals Limited" },
  { value: "NSE:ALKEM-EQ", label: "ALKEM", name: "Alkem Laboratories Limited" },
  { value: "NSE:ABBOTINDIA-EQ", label: "ABBOTINDIA", name: "Abbott India Limited" },
  { value: "NSE:APOLLOHOSP-EQ", label: "APOLLOHOSP", name: "Apollo Hospitals Enterprise Limited" },
  { value: "NSE:GLENMARK-EQ", label: "GLENMARK", name: "Glenmark Pharmaceuticals Limited" },
  { value: "NSE:CADILAHC-EQ", label: "CADILAHC", name: "Cadila Healthcare Limited" },
  { value: "NSE:IPCALAB-EQ", label: "IPCALAB", name: "IPCA Laboratories Limited" },
  { value: "NSE:LALPATHLAB-EQ", label: "LALPATHLAB", name: "Dr. Lal PathLabs Limited" },
  { value: "NSE:METROPOLIS-EQ", label: "METROPOLIS", name: "Metropolis Healthcare Limited" },
  { value: "NSE:MAXHEALTH-EQ", label: "MAXHEALTH", name: "Max Healthcare Institute Limited" },
  { value: "NSE:FORTIS-EQ", label: "FORTIS", name: "Fortis Healthcare Limited" },
  { value: "NSE:SANOFI-EQ", label: "SANOFI", name: "Sanofi India Limited" },
  { value: "NSE:PFIZER-EQ", label: "PFIZER", name: "Pfizer Limited" },

  // FMCG & Consumer Goods
  { value: "NSE:HINDUNILVR-EQ", label: "HINDUNILVR", name: "Hindustan Unilever Limited" },
  { value: "NSE:ITC-EQ", label: "ITC", name: "ITC Limited" },
  { value: "NSE:NESTLEIND-EQ", label: "NESTLEIND", name: "Nestle India Limited" },
  { value: "NSE:BRITANNIA-EQ", label: "BRITANNIA", name: "Britannia Industries Limited" },
  { value: "NSE:DABUR-EQ", label: "DABUR", name: "Dabur India Limited" },
  { value: "NSE:MARICO-EQ", label: "MARICO", name: "Marico Limited" },
  { value: "NSE:GODREJCP-EQ", label: "GODREJCP", name: "Godrej Consumer Products Limited" },
  { value: "NSE:COLPAL-EQ", label: "COLPAL", name: "Colgate Palmolive (India) Limited" },
  { value: "NSE:TATACONSUM-EQ", label: "TATACONSUM", name: "Tata Consumer Products Limited" },
  { value: "NSE:EMAMILTD-EQ", label: "EMAMILTD", name: "Emami Limited" },
  { value: "NSE:UBL-EQ", label: "UBL", name: "United Breweries Limited" },
  { value: "NSE:RADICO-EQ", label: "RADICO", name: "Radico Khaitan Limited" },
  { value: "NSE:MCDOWELL-N-EQ", label: "MCDOWELL-N", name: "United Spirits Limited" },
  { value: "NSE:PGHH-EQ", label: "PGHH", name: "Procter & Gamble Hygiene and Health Care Limited" },
  { value: "NSE:JYOTHYLAB-EQ", label: "JYOTHYLAB", name: "Jyothy Labs Limited" },
  { value: "NSE:VBL-EQ", label: "VBL", name: "Varun Beverages Limited" },
  { value: "NSE:GILLETTE-EQ", label: "GILLETTE", name: "Gillette India Limited" },

  // Automobiles & Auto Components
  { value: "NSE:MARUTI-EQ", label: "MARUTI", name: "Maruti Suzuki India Limited" },
  { value: "NSE:TATAMOTORS-EQ", label: "TATAMOTORS", name: "Tata Motors Limited" },
  { value: "NSE:M&M-EQ", label: "M&M", name: "Mahindra & Mahindra Limited" },
  { value: "NSE:EICHERMOT-EQ", label: "EICHERMOT", name: "Eicher Motors Limited" },
  { value: "NSE:HEROMOTOCO-EQ", label: "HEROMOTOCO", name: "Hero MotoCorp Limited" },
  { value: "NSE:BAJAJ-AUTO-EQ", label: "BAJAJ-AUTO", name: "Bajaj Auto Limited" },
  { value: "NSE:TVSMOTOR-EQ", label: "TVSMOTOR", name: "TVS Motor Company Limited" },
  { value: "NSE:ASHOKLEY-EQ", label: "ASHOKLEY", name: "Ashok Leyland Limited" },
  { value: "NSE:BOSCHLTD-EQ", label: "BOSCHLTD", name: "Bosch Limited" },
  { value: "NSE:MOTHERSON-EQ", label: "MOTHERSON", name: "Samvardhana Motherson International Limited" },
  { value: "NSE:BALKRISIND-EQ", label: "BALKRISIND", name: "Balkrishna Industries Limited" },
  { value: "NSE:MRF-EQ", label: "MRF", name: "MRF Limited" },
  { value: "NSE:APOLLOTYRE-EQ", label: "APOLLOTYRE", name: "Apollo Tyres Limited" },
  { value: "NSE:EXIDEIND-EQ", label: "EXIDEIND", name: "Exide Industries Limited" },
  { value: "NSE:BHARATFORG-EQ", label: "BHARATFORG", name: "Bharat Forge Limited" },
  { value: "NSE:ESCORTS-EQ", label: "ESCORTS", name: "Escorts Kubota Limited" },
  { value: "NSE:SWARAJENG-EQ", label: "SWARAJENG", name: "Swaraj Engines Limited" },
  { value: "NSE:ENDURANCE-EQ", label: "ENDURANCE", name: "Endurance Technologies Limited" },
  { value: "NSE:FINCABLES-EQ", label: "FINCABLES", name: "Finolex Cables Limited" },

  // Energy, Oil & Gas
  { value: "NSE:RELIANCE-EQ", label: "RELIANCE", name: "Reliance Industries Limited" },
  { value: "NSE:ONGC-EQ", label: "ONGC", name: "Oil and Natural Gas Corporation Limited" },
  { value: "NSE:BPCL-EQ", label: "BPCL", name: "Bharat Petroleum Corporation Limited" },
  { value: "NSE:IOC-EQ", label: "IOC", name: "Indian Oil Corporation Limited" },
  { value: "NSE:HINDPETRO-EQ", label: "HINDPETRO", name: "Hindustan Petroleum Corporation Limited" },
  { value: "NSE:GAIL-EQ", label: "GAIL", name: "GAIL (India) Limited" },
  { value: "NSE:PETRONET-EQ", label: "PETRONET", name: "Petronet LNG Limited" },
  { value: "NSE:OIL-EQ", label: "OIL", name: "Oil India Limited" },
  { value: "NSE:GSPL-EQ", label: "GSPL", name: "Gujarat State Petronet Limited" },
  { value: "NSE:IGL-EQ", label: "IGL", name: "Indraprastha Gas Limited" },
  { value: "NSE:MGL-EQ", label: "MGL", name: "Mahanagar Gas Limited" },
  { value: "NSE:GUJGASLTD-EQ", label: "GUJGASLTD", name: "Gujarat Gas Limited" },

  // Power & Utilities
  { value: "NSE:NTPC-EQ", label: "NTPC", name: "NTPC Limited" },
  { value: "NSE:POWERGRID-EQ", label: "POWERGRID", name: "Power Grid Corporation of India Limited" },
  { value: "NSE:ADANIPOWER-EQ", label: "ADANIPOWER", name: "Adani Power Limited" },
  { value: "NSE:TATAPOWER-EQ", label: "TATAPOWER", name: "Tata Power Company Limited" },
  { value: "NSE:ADANIGREEN-EQ", label: "ADANIGREEN", name: "Adani Green Energy Limited" },
  { value: "NSE:TORNTPOWER-EQ", label: "TORNTPOWER", name: "Torrent Power Limited" },
  { value: "NSE:NHPC-EQ", label: "NHPC", name: "NHPC Limited" },
  { value: "NSE:SJVN-EQ", label: "SJVN", name: "SJVN Limited" },
  { value: "NSE:THERMAX-EQ", label: "THERMAX", name: "Thermax Limited" },
  { value: "NSE:JINDALSAW-EQ", label: "JINDALSAW", name: "Jindal Saw Limited" },

  // Metals & Mining
  { value: "NSE:TATASTEEL-EQ", label: "TATASTEEL", name: "Tata Steel Limited" },
  { value: "NSE:JSWSTEEL-EQ", label: "JSWSTEEL", name: "JSW Steel Limited" },
  { value: "NSE:HINDALCO-EQ", label: "HINDALCO", name: "Hindalco Industries Limited" },
  { value: "NSE:COALINDIA-EQ", label: "COALINDIA", name: "Coal India Limited" },
  { value: "NSE:VEDL-EQ", label: "VEDL", name: "Vedanta Limited" },
  { value: "NSE:SAIL-EQ", label: "SAIL", name: "Steel Authority of India Limited" },
  { value: "NSE:JINDALSTEL-EQ", label: "JINDALSTEL", name: "Jindal Steel & Power Limited" },
  { value: "NSE:NMDC-EQ", label: "NMDC", name: "NMDC Limited" },
  { value: "NSE:HINDZINC-EQ", label: "HINDZINC", name: "Hindustan Zinc Limited" },
  { value: "NSE:NATIONALUM-EQ", label: "NATIONALUM", name: "National Aluminium Company Limited" },
  { value: "NSE:MOIL-EQ", label: "MOIL", name: "MOIL Limited" },
  { value: "NSE:APLAPOLLO-EQ", label: "APLAPOLLO", name: "APL Apollo Tubes Limited" },
  { value: "NSE:RATNAMANI-EQ", label: "RATNAMANI", name: "Ratnamani Metals & Tubes Limited" },

  // Telecom
  { value: "NSE:BHARTIARTL-EQ", label: "BHARTIARTL", name: "Bharti Airtel Limited" },
  { value: "NSE:IDEA-EQ", label: "IDEA", name: "Vodafone Idea Limited" },
  { value: "NSE:TATACOMM-EQ", label: "TATACOMM", name: "Tata Communications Limited" },
  { value: "NSE:ITI-EQ", label: "ITI", name: "ITI Limited" },

  // Cement
  { value: "NSE:ULTRACEMCO-EQ", label: "ULTRACEMCO", name: "UltraTech Cement Limited" },
  { value: "NSE:SHREECEM-EQ", label: "SHREECEM", name: "Shree Cement Limited" },
  { value: "NSE:GRASIM-EQ", label: "GRASIM", name: "Grasim Industries Limited" },
  { value: "NSE:ACC-EQ", label: "ACC", name: "ACC Limited" },
  { value: "NSE:AMBUJACEM-EQ", label: "AMBUJACEM", name: "Ambuja Cements Limited" },
  { value: "NSE:JKCEMENT-EQ", label: "JKCEMENT", name: "JK Cement Limited" },
  { value: "NSE:RAMCOCEM-EQ", label: "RAMCOCEM", name: "The Ramco Cements Limited" },
  { value: "NSE:DALMIACEMT-EQ", label: "DALMIACEMT", name: "Dalmia Bharat Limited" },
  { value: "NSE:INDIACEM-EQ", label: "INDIACEM", name: "India Cements Limited" },
  { value: "NSE:ORIENTCEM-EQ", label: "ORIENTCEM", name: "Orient Cement Limited" },

  // Infrastructure & Construction
  { value: "NSE:LT-EQ", label: "LT", name: "Larsen & Toubro Limited" },
  { value: "NSE:ADANIPORTS-EQ", label: "ADANIPORTS", name: "Adani Ports and Special Economic Zone Limited" },
  { value: "NSE:DLF-EQ", label: "DLF", name: "DLF Limited" },
  { value: "NSE:GODREJPROP-EQ", label: "GODREJPROP", name: "Godrej Properties Limited" },
  { value: "NSE:OBEROIRLTY-EQ", label: "OBEROIRLTY", name: "Oberoi Realty Limited" },
  { value: "NSE:PHOENIXLTD-EQ", label: "PHOENIXLTD", name: "Phoenix Mills Limited" },
  { value: "NSE:PRESTIGE-EQ", label: "PRESTIGE", name: "Prestige Estates Projects Limited" },
  { value: "NSE:BRIGADE-EQ", label: "BRIGADE", name: "Brigade Enterprises Limited" },
  { value: "NSE:SUNTECK-EQ", label: "SUNTECK", name: "Sunteck Realty Limited" },
  { value: "NSE:IRB-EQ", label: "IRB", name: "IRB Infrastructure Developers Limited" },
  { value: "NSE:GMRINFRA-EQ", label: "GMRINFRA", name: "GMR Infrastructure Limited" },
  { value: "NSE:NBCC-EQ", label: "NBCC", name: "NBCC (India) Limited" },
  { value: "NSE:PNC-EQ", label: "PNC", name: "Pritish Nandy Communications Limited" },
  { value: "NSE:KNR-EQ", label: "KNR", name: "KNR Constructions Limited" },

  // Chemicals & Fertilizers
  { value: "NSE:UPL-EQ", label: "UPL", name: "UPL Limited" },
  { value: "NSE:PIDILITIND-EQ", label: "PIDILITIND", name: "Pidilite Industries Limited" },
  { value: "NSE:AARTI-EQ", label: "AARTI", name: "Aarti Industries Limited" },
  { value: "NSE:DEEPAKNTR-EQ", label: "DEEPAKNTR", name: "Deepak Nitrite Limited" },
  { value: "NSE:SRF-EQ", label: "SRF", name: "SRF Limited" },
  { value: "NSE:CHAMBLFERT-EQ", label: "CHAMBLFERT", name: "Chambal Fertilizers & Chemicals Limited" },
  { value: "NSE:TATACHEM-EQ", label: "TATACHEM", name: "Tata Chemicals Limited" },
  { value: "NSE:GNFC-EQ", label: "GNFC", name: "Gujarat Narmada Valley Fertilizers & Chemicals Limited" },
  { value: "NSE:COROMANDEL-EQ", label: "COROMANDEL", name: "Coromandel International Limited" },
  { value: "NSE:BALRAMCHIN-EQ", label: "BALRAMCHIN", name: "Balrampur Chini Mills Limited" },
  { value: "NSE:PIIND-EQ", label: "PIIND", name: "PI Industries Limited" },
  { value: "NSE:SUDARSCHEM-EQ", label: "SUDARSCHEM", name: "Sudarshan Chemical Industries Limited" },
  { value: "NSE:NAVINFLUOR-EQ", label: "NAVINFLUOR", name: "Navin Fluorine International Limited" },
  { value: "NSE:ALKYLAMINE-EQ", label: "ALKYLAMINE", name: "Alkyl Amines Chemicals Limited" },
  { value: "NSE:ATUL-EQ", label: "ATUL", name: "Atul Limited" },
  { value: "NSE:VINDHYATEL-EQ", label: "VINDHYATEL", name: "Vindhya Telelinks Limited" },

  // Retail & E-commerce
  { value: "NSE:DMART-EQ", label: "DMART", name: "Avenue Supermarts Limited (DMart)" },
  { value: "NSE:TRENT-EQ", label: "TRENT", name: "Trent Limited" },
  { value: "NSE:JUBLFOOD-EQ", label: "JUBLFOOD", name: "Jubilant FoodWorks Limited" },
  { value: "NSE:TITAN-EQ", label: "TITAN", name: "Titan Company Limited" },
  { value: "NSE:PAGEIND-EQ", label: "PAGEIND", name: "Page Industries Limited" },
  { value: "NSE:SHOPERSTOP-EQ", label: "SHOPERSTOP", name: "Shoppers Stop Limited" },
  { value: "NSE:VMART-EQ", label: "VMART", name: "V-Mart Retail Limited" },
  { value: "NSE:SPENCERS-EQ", label: "SPENCERS", name: "Spencer's Retail Limited" },
  { value: "NSE:ADITYA-EQ", label: "ADITYA", name: "Aditya Birla Fashion and Retail Limited" },

  // Paints & Home Improvement
  { value: "NSE:ASIANPAINT-EQ", label: "ASIANPAINT", name: "Asian Paints Limited" },
  { value: "NSE:BERGER-EQ", label: "BERGER", name: "Berger Paints India Limited" },
  { value: "NSE:KANSAINER-EQ", label: "KANSAINER", name: "Kansai Nerolac Paints Limited" },
  { value: "NSE:AKZOINDIA-EQ", label: "AKZOINDIA", name: "Akzo Nobel India Limited" },
  { value: "NSE:INDIGO-EQ", label: "INDIGO", name: "Indigo Paints Limited" },
  { value: "NSE:HAVELLS-EQ", label: "HAVELLS", name: "Havells India Limited" },
  { value: "NSE:CROMPTON-EQ", label: "CROMPTON", name: "Crompton Greaves Consumer Electricals Limited" },
  { value: "NSE:VOLTAS-EQ", label: "VOLTAS", name: "Voltas Limited" },
  { value: "NSE:BLUESTARCO-EQ", label: "BLUESTARCO", name: "Blue Star Limited" },
  { value: "NSE:POLYCAB-EQ", label: "POLYCAB", name: "Polycab India Limited" },
  { value: "NSE:KEI-EQ", label: "KEI", name: "KEI Industries Limited" },
  { value: "NSE:FINOLEX-EQ", label: "FINOLEX", name: "Finolex Industries Limited" },

  // Media & Entertainment
  { value: "NSE:ZEEL-EQ", label: "ZEEL", name: "Zee Entertainment Enterprises Limited" },
  { value: "NSE:SUNTV-EQ", label: "SUNTV", name: "Sun TV Network Limited" },
  { value: "NSE:PVRINOX-EQ", label: "PVRINOX", name: "PVR INOX Limited" },
  { value: "NSE:SAREGAMA-EQ", label: "SAREGAMA", name: "Saregama India Limited" },
  { value: "NSE:NAZARA-EQ", label: "NAZARA", name: "Nazara Technologies Limited" },
  { value: "NSE:TIPS-EQ", label: "TIPS", name: "Tips Industries Limited" },

  // Hotels & Tourism
  { value: "NSE:INDHOTEL-EQ", label: "INDHOTEL", name: "Indian Hotels Company Limited" },
  { value: "NSE:LEMONTREE-EQ", label: "LEMONTREE", name: "Lemon Tree Hotels Limited" },
  { value: "NSE:CHALET-EQ", label: "CHALET", name: "Chalet Hotels Limited" },
  { value: "NSE:MAHLIFE-EQ", label: "MAHLIFE", name: "Mahindra Lifespace Developers Limited" },
  { value: "NSE:EIH-EQ", label: "EIH", name: "EIH Limited" },
  { value: "NSE:TAJGVK-EQ", label: "TAJGVK", name: "Taj GVK Hotels & Resorts Limited" },

  // Textiles & Apparel
  { value: "NSE:GOKEX-EQ", label: "GOKEX", name: "Gokal Mahavir Infra Limited" },
  { value: "NSE:ARVIND-EQ", label: "ARVIND", name: "Arvind Limited" },
  { value: "NSE:WELSPUNIND-EQ", label: "WELSPUNIND", name: "Welspun India Limited" },
  { value: "NSE:TRIDENT-EQ", label: "TRIDENT", name: "Trident Limited" },
  { value: "NSE:RAYMOND-EQ", label: "RAYMOND", name: "Raymond Limited" },
  { value: "NSE:SWARAJMAZ-EQ", label: "SWARAJMAZ", name: "Swaraj Mazda Limited" },

  // Conglomerates & Diversified
  { value: "NSE:ADANIENT-EQ", label: "ADANIENT", name: "Adani Enterprises Limited" },
  { value: "NSE:ADANITRANS-EQ", label: "ADANITRANS", name: "Adani Transmission Limited" },
  { value: "NSE:ADANIENSOL-EQ", label: "ADANIENSOL", name: "Adani Energy Solutions Limited" },
  { value: "NSE:ADANIWILMAR-EQ", label: "ADANIWILMAR", name: "Adani Wilmar Limited" },
  { value: "NSE:TATAINVEST-EQ", label: "TATAINVEST", name: "Tata Investment Corporation Limited" },

  // Engineering & Capital Goods
  { value: "NSE:BHARATFORG-EQ", label: "BHARATFORG", name: "Bharat Forge Limited" },
  { value: "NSE:CUMMINSIND-EQ", label: "CUMMINSIND", name: "Cummins India Limited" },
  { value: "NSE:ABB-EQ", label: "ABB", name: "ABB India Limited" },
  { value: "NSE:SIEMENS-EQ", label: "SIEMENS", name: "Siemens Limited" },
  { value: "NSE:SKFINDIA-EQ", label: "SKFINDIA", name: "SKF India Limited" },
  { value: "NSE:SCHAEFFLER-EQ", label: "SCHAEFFLER", name: "Schaeffler India Limited" },
  { value: "NSE:TIMKEN-EQ", label: "TIMKEN", name: "Timken India Limited" },
  { value: "NSE:KAJARIACER-EQ", label: "KAJARIACER", name: "Kajaria Ceramics Limited" },
  { value: "NSE:ORIENTELEC-EQ", label: "ORIENTELEC", name: "Orient Electric Limited" },
  { value: "NSE:CROMPTON-EQ", label: "CROMPTON", name: "Crompton Greaves Consumer Electricals Limited" },
  { value: "NSE:WHIRLPOOL-EQ", label: "WHIRLPOOL", name: "Whirlpool of India Limited" },
  { value: "NSE:VGUARD-EQ", label: "VGUARD", name: "V-Guard Industries Limited" },
  { value: "NSE:GRINDWELL-EQ", label: "GRINDWELL", name: "Grindwell Norton Limited" },

  // Logistics & Transportation
  { value: "NSE:CONCOR-EQ", label: "CONCOR", name: "Container Corporation of India Limited" },
  { value: "NSE:BLUEDART-EQ", label: "BLUEDART", name: "Blue Dart Express Limited" },
  { value: "NSE:VRL-EQ", label: "VRL", name: "VRL Logistics Limited" },
  { value: "NSE:TCI-EQ", label: "TCI", name: "Transport Corporation of India Limited" },
  { value: "NSE:MAHLOG-EQ", label: "MAHLOG", name: "Mahindra Logistics Limited" },
  { value: "NSE:AEGISLOG-EQ", label: "AEGISLOG", name: "Aegis Logistics Limited" },

  // Specialty Chemicals & Diagnostics
  { value: "NSE:LALPATHLAB-EQ", label: "LALPATHLAB", name: "Dr. Lal PathLabs Limited" },
  { value: "NSE:METROPOLIS-EQ", label: "METROPOLIS", name: "Metropolis Healthcare Limited" },
  { value: "NSE:THYROCARE-EQ", label: "THYROCARE", name: "Thyrocare Technologies Limited" },

  // Plastics & Packaging
  { value: "NSE:ASTRAL-EQ", label: "ASTRAL", name: "Astral Limited" },
  { value: "NSE:SUPREMEIND-EQ", label: "SUPREMEIND", name: "Supreme Industries Limited" },
  { value: "NSE:NILKAMAL-EQ", label: "NILKAMAL", name: "Nilkamal Limited" },
  { value: "NSE:UFLEX-EQ", label: "UFLEX", name: "Uflex Limited" },
  { value: "NSE:HUHTAMAKI-EQ", label: "HUHTAMAKI", name: "Huhtamaki India Limited" },
  { value: "NSE:MAXVIL-EQ", label: "MAXVIL", name: "Max Ventures and Industries Limited" },

  // Defence & Aerospace
  { value: "NSE:HAL-EQ", label: "HAL", name: "Hindustan Aeronautics Limited" },
  { value: "NSE:BEL-EQ", label: "BEL", name: "Bharat Electronics Limited" },
  { value: "NSE:COCHINSHIP-EQ", label: "COCHINSHIP", name: "Cochin Shipyard Limited" },
  { value: "NSE:GRSE-EQ", label: "GRSE", name: "Garden Reach Shipbuilders & Engineers Limited" },
  { value: "NSE:MIDHANI-EQ", label: "MIDHANI", name: "Mishra Dhatu Nigam Limited" },

  // Jewellery
  { value: "NSE:KALYANKJIL-EQ", label: "KALYANKJIL", name: "Kalyan Jewellers India Limited" },
  { value: "NSE:TITAN-EQ", label: "TITAN", name: "Titan Company Limited" },
  { value: "NSE:RAJESHEXPO-EQ", label: "RAJESHEXPO", name: "Rajesh Exports Limited" },

  // Paper & Printing
  { value: "NSE:TNPL-EQ", label: "TNPL", name: "Tamil Nadu Newsprint & Papers Limited" },
  { value: "NSE:BALKRISHNA-EQ", label: "BALKRISHNA", name: "Balkrishna Paper Mills Limited" },
  { value: "NSE:ORIENTA-EQ", label: "ORIENTA", name: "Oriental Paper & Industries Limited" },

  // Sugar & Distillery
  { value: "NSE:BALRAMCHIN-EQ", label: "BALRAMCHIN", name: "Balrampur Chini Mills Limited" },
  { value: "NSE:TRIVENI-EQ", label: "TRIVENI", name: "Triveni Engineering & Industries Limited" },
  { value: "NSE:DHAMPUR-EQ", label: "DHAMPUR", name: "Dhampur Sugar Mills Limited" },
  { value: "NSE:DWARIKESH-EQ", label: "DWARIKESH", name: "Dwarikesh Sugar Industries Limited" },
  { value: "NSE:BAJAJHIND-EQ", label: "BAJAJHIND", name: "Bajaj Hindusthan Sugar Limited" },

  // Tea & Plantation
  { value: "NSE:MCLEODRUSS-EQ", label: "MCLEODRUSS", name: "Mcleod Russel India Limited" },
  { value: "NSE:JAYSHREETE-EQ", label: "JAYSHREETE", name: "Jayshree Tea & Industries Limited" },
  { value: "NSE:HARRMALAYA-EQ", label: "HARRMALAYA", name: "Harrison Malayalam Limited" },

  // Glass & Ceramics
  { value: "NSE:HSIL-EQ", label: "HSIL", name: "HSIL Limited" },
  { value: "NSE:CIPLAQLTY-EQ", label: "CIPLAQLTY", name: "Cipla Quality Chemical Industries Limited" },
  { value: "NSE:HSIL-EQ", label: "HSIL", name: "HSIL Limited" },

  // Leather & Footwear
  { value: "NSE:RELAXO-EQ", label: "RELAXO", name: "Relaxo Footwears Limited" },
  { value: "NSE:MIRZA-EQ", label: "MIRZA", name: "Mirza International Limited" },

  // Additional Mid & Small Cap Stocks
  { value: "NSE:Dixon-EQ", label: "DIXON", name: "Dixon Technologies (India) Limited" },
  { value: "NSE:SYRMA-EQ", label: "SYRMA", name: "Syrma SGS Technology Limited" },
  { value: "NSE:CLEAN-EQ", label: "CLEAN", name: "Clean Science and Technology Limited" },
  { value: "NSE:FINEORG-EQ", label: "FINEORG", name: "Fine Organic Industries Limited" },
  { value: "NSE:LATENTVIEW-EQ", label: "LATENTVIEW", name: "Latent View Analytics Limited" },
  { value: "NSE:NEWGEN-EQ", label: "NEWGEN", name: "Newgen Software Technologies Limited" },
  { value: "NSE:HAPPSTMNDS-EQ", label: "HAPPSTMNDS", name: "Happiest Minds Technologies Limited" },
  { value: "NSE:INTELLECT-EQ", label: "INTELLECT", name: "Intellect Design Arena Limited" },
  { value: "NSE:KPITTECH-EQ", label: "KPITTECH", name: "KPIT Technologies Limited" },
  { value: "NSE:TATATECH-EQ", label: "TATATECH", name: "Tata Technologies Limited" },
  { value: "NSE:RTNINDIA-EQ", label: "RTNINDIA", name: "RateGain Travel Technologies Limited" },
  { value: "NSE:BRIGADE-EQ", label: "BRIGADE", name: "Brigade Enterprises Limited" },
  { value: "NSE:MACROTECH-EQ", label: "MACROTECH", name: "Macrotech Developers Limited" },
  { value: "NSE:LODHA-EQ", label: "LODHA", name: "Lodha Developers Limited" },
  { value: "NSE:SIGNATURE-EQ", label: "SIGNATURE", name: "Signature Global (India) Limited" },
  { value: "NSE:JKPAPER-EQ", label: "JKPAPER", name: "JK Paper Limited" },
  { value: "NSE:SESAGOA-EQ", label: "SESAGOA", name: "Sesa Goa Limited" },
  { value: "NSE:GESHIP-EQ", label: "GESHIP", name: "Great Eastern Shipping Company Limited" },
  { value: "NSE:CRISIL-EQ", label: "CRISIL", name: "CRISIL Limited" },
  { value: "NSE:CDSL-EQ", label: "CDSL", name: "Central Depository Services (India) Limited" },
  { value: "NSE:NAUKRI-EQ", label: "NAUKRI", name: "Info Edge (India) Limited" },
  { value: "NSE:AFFLE-EQ", label: "AFFLE", name: "Affle (India) Limited" },
  { value: "NSE:MOTILALOFS-EQ", label: "MOTILALOFS", name: "Motilal Oswal Financial Services Limited" },
  { value: "NSE:IIFLWAM-EQ", label: "IIFLWAM", name: "IIFL Wealth Management Limited" },
  { value: "NSE:ANGELONE-EQ", label: "ANGELONE", name: "Angel One Limited" },
  { value: "NSE:CREDITACC-EQ", label: "CREDITACC", name: "CreditAccess Grameen Limited" },
  { value: "NSE:SPANDANA-EQ", label: "SPANDANA", name: "Spandana Sphoorty Financial Limited" },
  { value: "NSE:SBFC-EQ", label: "SBFC", name: "SBFC Finance Limited" },
  { value: "NSE:UJJIVAN-EQ", label: "UJJIVAN", name: "Ujjivan Small Finance Bank Limited" },
  { value: "NSE:EQUITAS-EQ", label: "EQUITAS", name: "Equitas Small Finance Bank Limited" },
  { value: "NSE:AUBANK-EQ", label: "AUBANK", name: "AU Small Finance Bank Limited" },
  { value: "NSE:INDOSTAR-EQ", label: "INDOSTAR", name: "IndoStar Capital Finance Limited" },
  { value: "NSE:AAVAS-EQ", label: "AAVAS", name: "Aavas Financiers Limited" },
  { value: "NSE:HOMEFIRST-EQ", label: "HOMEFIRST", name: "Home First Finance Company India Limited" },
  { value: "NSE:CAPLIPOINT-EQ", label: "CAPLIPOINT", name: "Caplin Point Laboratories Limited" },
  { value: "NSE:LAURUS-EQ", label: "LAURUS", name: "Laurus Labs Limited" },
  { value: "NSE:SPARC-EQ", label: "SPARC", name: "Sun Pharma Advanced Research Company Limited" },
  { value: "NSE:SYNGENE-EQ", label: "SYNGENE", name: "Syngene International Limited" },
  { value: "NSE:SEQUENT-EQ", label: "SEQUENT", name: "Sequent Scientific Limited" },
  { value: "NSE:NATCOPHAR-EQ", label: "NATCOPHAR", name: "Natco Pharma Limited" },
  { value: "NSE:GRANULES-EQ", label: "GRANULES", name: "Granules India Limited" },
  { value: "NSE:STERLITE-EQ", label: "STERLITE", name: "Sterlite Technologies Limited" },
  { value: "NSE:JUBLPHARMA-EQ", label: "JUBLPHARMA", name: "Jubilant Pharmova Limited" },
];

// Helper function to normalize symbol format
export const normalizeSymbol = (sym) => {
  if (!sym) return "";
  const trimmed = sym.trim().toUpperCase();
  if (trimmed.includes(":")) return trimmed;
  return `NSE:${trimmed}-EQ`;
};
